// Code generated by protoc-gen-go-structtags. DO NOT EDIT.

package proto

type HelloRequest struct {
	Name string `json:"name" bun:"name"`
}
type HelloResponse struct {
	Message string `json:"message" bun:"message"`
}
type User struct {
	Id                int32  `json:"id" bun:"id"`
	Name              string `json:"name" bun:"name"`
	Email             string `json:"email" bun:"email"`
	Password          string `json:"password" bun:"password"`
	Phone             string `json:"phone" bun:"phone"`
	Address           string `json:"address" bun:"address"`
	City              string `json:"city" bun:"city"`
	State             string `json:"state" bun:"state"`
	Country           string `json:"country" bun:"country"`
	Zip               string `json:"zip" bun:"zip"`
	CreatedAt         string `json:"createdAt" bun:"createdAt"`
	UpdatedAt         string `json:"updatedAt" bun:"updatedAt"`
	DeletedAt         string `json:"deletedAt" bun:"deletedAt"`
	LastLogin         string `json:"lastLogin" bun:"lastLogin"`
	LastLoginIp       string `json:"lastLoginIp" bun:"lastLoginIp"`
	LastLoginLocation string `json:"lastLoginLocation" bun:"lastLoginLocation"`
}
